apiVersion: batch/v1
kind: Job
metadata:
  name: fortio
spec:
  template:
    spec:
      volumes:
      - name: shared
        emptyDir: {}
      containers:
      - name: fortio
        image: fortio/fortio
        command: ["fortio", "load", "-t", "60s", "-qps", "2000", http://192.168.49.2:30007/]
        volumeMounts:
        - name: shared
          mountPath: /shared              
      restartPolicy: Never